// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xDBmygQPi48-fj44P80raeXdo6h5wcI',
    appId: '1:1076835651206:web:5ba183f7001c33e73e4b07',
    messagingSenderId: '1076835651206',
    projectId: 'words-lists',
    authDomain: 'words-lists.firebaseapp.com',
    storageBucket: 'words-lists.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2WpKLKMubMC-Y05tic05-Ud4vfBM52hw',
    appId: '1:1076835651206:android:8f2125d0563adfe43e4b07',
    messagingSenderId: '1076835651206',
    projectId: 'words-lists',
    storageBucket: 'words-lists.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuYT_blX--VFCmDovRj8BRulyXwu_Z_e4',
    appId: '1:1076835651206:ios:0ed38b233921cdbf3e4b07',
    messagingSenderId: '1076835651206',
    projectId: 'words-lists',
    storageBucket: 'words-lists.appspot.com',
    iosBundleId: 'com.example.findTheWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuYT_blX--VFCmDovRj8BRulyXwu_Z_e4',
    appId: '1:1076835651206:ios:7a794905021c3b543e4b07',
    messagingSenderId: '1076835651206',
    projectId: 'words-lists',
    storageBucket: 'words-lists.appspot.com',
    iosBundleId: 'com.example.findTheWords.RunnerTests',
  );
}
